#-------------------------------
# General Site Settings

title: Teodora Drozdik-Popović
description: Mezzo-soprano
email: tdrozdikpopovic@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Videos, url: '#videos'}
- {name: Gallery, url: '#gallery'}
- {name: Biography, url: '#biography'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  **Teodora Drozdik-Popović** </br> is a Serbian born **Mezzo-Soprano**, living in the Netherlands.


# skills:
# - {name: Communication, value: '9'}
# - {name: Organization, value: '7'}
# - {name: Learning, value: '10'}
# - {name: Teaching, value: '6'}
# - {name: Planning, value: '7'}
# - {name: Visual Design, value: '5'}
# - {name: UX Design, value: '8'}
# - {name: Programming, value: '6'}

#-------------------------------
# Videos Section

videos:
- {title: 'Luciano Berio: Folk Songs',
   url: 'AxA09gZTXr8'}
- {title: 'L. Bernstein: I am easily assimilated',
   url: 'UZvuKOTTeSE'}
- {title: 'Alexey Verstovsky: Stari Muzh',
   url: '7ZMOmua3pFY'}

#-------------------------------
# Gallery Section

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'gallery/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'gallery/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'gallery/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'gallery/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'gallery/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'gallery/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'gallery/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'gallery/proj-8.html'}




#-------------------------------
# Biography Section

biography:
- {
  title: 'Director of Design, OnToText Ind.',
  quote: '<p>The Serbian born mezzo-soprano, Teodora Drozdik-Popović grew up in Novi Sad, Serbia in
a family of musicians. Before pursuing her singing ambitions, she studied Hungarian
language and literature at the Faculty of Philosophy in Novi Sad for which she holds a
master’s degree.</p><p>In 2012 Teodora began her bachelor in classical singing at Codarts,
Rotterdam with Carolyn Watkinson. She graduated in March 2016 in the class of Charlotte
Riedijk. Currently, she is a second year master student at the Maastricht Conservatory in the
class of Axel Everaert.</p><p>Teodora is mostly concentrating on opera and lied repertoire. She
gave solo recitals with her duo partner in Serbia, Belgium and The Netherlands. On stage
she appeared in roles such as Componist (Ariadne auf Naxos), Amadigi (Amadigi di Gaula),
Elsa (Faust-opera pastiche), Zelatrice (Suor Angelica), Dritte Dame and Dritter Knabe (Die
Zauberflöte), The Old Lady (Candide-concertante). </p> She participated
in master classes given by Damien Guillon, Roberta Alexander, Maria Acda, Renate Behle,
Maria Riccarda Wesseling and Claron McFadden. </p><p> She won the first prize on De Stem van
Haarlem competition, the first prize and special prize for interpretation at the “Vera Kovač
Vitkai” competition and was the finalist of the Prix d’Harmonie competition. </p>',
  logo: 'uns.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCZMYpMTeHKFsA98k-l8fSzA'}
- {icon: 'linkedin', link: ''}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
